name: 'DDR Security: Base security recipe'
description: 'Base recipe that contains all security recipes.'
type: 'Droptica’s Drupal Recipes'
recipes:
  - ddr_security_password_policy
  - ddr_security_email_notifications_email_changed
  - ddr_security_email_notifications_password_changed
  - ddr_security_email_notifications_role_changed
  - ddr_security_automated_logout
  - ddr_security_session_limit
  - ddr_security_login