name: 'Saplings'
description: 'Modern Drupal starter recipe.'
type: 'Site'
recipes:
  - ddr_security_password_policy
  - ddr_security_email_notifications_email_changed
  - ddr_security_email_notifications_password_changed
  - ddr_security_email_notifications_role_changed
  - ddr_security_automated_logout
  - ddr_security_session_limit
  - ddr_security_login
  - ddr_security_seckit